<a href="https://colab.research.google.com/github/geodavid14/Phishing_Analysis/blob/main/Diabetes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix
data = pd.read_csv('https://raw.githubusercontent.com/kdemertzis/EKPA/main/Data/phishing_dataset.csv', delimiter=',')

In [2]:
data = data.sample(frac=1).reset_index(drop=True)
data.head()

Domain  Have_IP  Have_At  \
0                                      allegro.pl        0        0   
1                                    katproxy.com        0        0   
2                                   nametests.com        0        0   
3                              mail.damclub020.nl        0        0   
4  hltps-wwv-bancoripley-cl.publicidadtechtre.com        0        0   

   URL_Length  URL_Depth  Redirection  https_Domain  TinyURL  Prefix/Suffix  \
0           1          2            0             0        0              0   
1           1          1            0             0        0              0   
2           1          3            0             0        0              0   
3           1          2            0             0        0              0   
4           1          1            0             0        0              1   

   DNS_Record  Web_Traffic  Domain_Age  Domain_End  iFrame  Mouse_Over  \
0           0            1           0           0       0           0   
1           0            0           0           0       0           0   
2           0            0           0           1       0           0   
3           0            1           1           1       0           0   
4           0            1           0           1       0           0   

   Right_Click  Web_Forwards  Label  
0            1             1      0  
1            1             0      0  
2            1             0      0  
3            1             0      1  
4            1             0      1

In [3]:
X = data.drop(['Domain', 'Label'], axis=1)

In [4]:
X.head()

Have_IP  Have_At  URL_Length  URL_Depth  Redirection  https_Domain  \
0        0        0           1          2            0             0   
1        0        0           1          1            0             0   
2        0        0           1          3            0             0   
3        0        0           1          2            0             0   
4        0        0           1          1            0             0   

   TinyURL  Prefix/Suffix  DNS_Record  Web_Traffic  Domain_Age  Domain_End  \
0        0              0           0            1           0           0   
1        0              0           0            0           0           0   
2        0              0           0            0           0           1   
3        0              0           0            1           1           1   
4        0              1           0            1           0           1   

   iFrame  Mouse_Over  Right_Click  Web_Forwards  
0       0           0            1             1  
1       0           0            1             0  
2       0           0            1             0  
3       0           0            1             0  
4       0           0            1             0

In [5]:
#y=np.ravel(data['Label'])
y=np.ravel(data['Label'])

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X,y, test_size = 0.3, random_state=43)

In [7]:
# Standardize the features
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [8]:
# Define classifiers
classifiers = [
    LogisticRegression(),
    SVC(),
    RandomForestClassifier(),
    MLPClassifier(),
    KNeighborsClassifier(),
    DecisionTreeClassifier()
]

In [9]:
# Evaluate and compare classifiers
results = {'Classifier': [], 'Accuracy': [], 'Precision': [], 'Recall': [], 'F1 Score': []}

for clf in classifiers:
    clf_name = clf.__class__.__name__

    # Train the classifier
    clf.fit(X_train, y_train)

    # Make predictions
    y_pred = clf.predict(X_test)

    # Calculate evaluation metrics
    acc = accuracy_score(y_test, y_pred)
    precision = precision_score(y_test, y_pred, average='weighted')
    recall = recall_score(y_test, y_pred, average='weighted')
    f1 = f1_score(y_test, y_pred, average='weighted')

    # Confusion matrix
    cm = confusion_matrix(y_test, y_pred)

    # Display results
    print(f"\n{clf_name} Metrics:")
    print(f"Accuracy: {acc}")
    print(f"Precision: {precision}")
    print(f"Recall: {recall}")
    print(f"F1 Score: {f1}")
    print("Confusion Matrix:")
    print(cm)

    # Store results for comparison
    results['Classifier'].append(clf_name)
    results['Accuracy'].append(acc)
    results['Precision'].append(precision)
    results['Recall'].append(recall)
    results['F1 Score'].append(f1)


LogisticRegression Metrics:
Accuracy: 0.793
Precision: 0.8228149238223748
Recall: 0.793
F1 Score: 0.7879694624552673
Confusion Matrix:
[[1423   82]
 [ 539  956]]

SVC Metrics:
Accuracy: 0.819
Precision: 0.8547589950021708
Recall: 0.819
F1 Score: 0.8142017653883774
Confusion Matrix:
[[1472   33]
 [ 510  985]]

RandomForestClassifier Metrics:
Accuracy: 0.86
Precision: 0.8705583212203477
Recall: 0.86
F1 Score: 0.8589487659098727
Confusion Matrix:
[[1422   83]
 [ 337 1158]]

MLPClassifier Metrics:
Accuracy: 0.8436666666666667
Precision: 0.8678046379713046
Recall: 0.8436666666666667
F1 Score: 0.8409784646232793
Confusion Matrix:
[[1463   42]
 [ 427 1068]]

KNeighborsClassifier Metrics:
Accuracy: 0.8343333333333334
Precision: 0.8371793470849572
Recall: 0.8343333333333334
F1 Score: 0.8339511547689287
Confusion Matrix:
[[1326  179]
 [ 318 1177]]

DecisionTreeClassifier Metrics:
Accuracy: 0.8576666666666667
Precision: 0.8682402553763441
Recall: 0.8576666666666667
F1 Score: 0.8565895762584537
C

In [10]:
# Display comparison results
results_df = pd.DataFrame(results)
results_df = results_df.sort_values(by='Accuracy', ascending=False)
print("\nComparison of Classifiers:")
print(results_df)


Comparison of Classifiers:
               Classifier  Accuracy  Precision    Recall  F1 Score
2  RandomForestClassifier  0.860000   0.870558  0.860000  0.858949
5  DecisionTreeClassifier  0.857667   0.868240  0.857667  0.856590
3           MLPClassifier  0.843667   0.867805  0.843667  0.840978
4    KNeighborsClassifier  0.834333   0.837179  0.834333  0.833951
1                     SVC  0.819000   0.854759  0.819000  0.814202
0      LogisticRegression  0.793000   0.822815  0.793000  0.787969
